export const killers = [
  { name: 'Trapper', perks: ['Brutal Strength', 'Agitation', 'Unnerving Presence']},
  { name: 'Wraith', perks: ['Predator', 'Bloodhound', 'Shadowborn']},
  { name: 'Hillbilly', perks: ['Enduring', 'Lightborn', 'Tinkerer']},
  { name: 'Nurse', perks: ['Stridor', 'Thanatophobia', "A Nurse's Calling"]},
  { name: 'The Shape', perks: ['Play with Your Food', 'Save the Best for Last', 'Dying Light']},
  { name: 'Hag', perks: ['Hex: Devour Hope', 'Hex: Ruin', 'Hex: Third Seal']},
  { name: 'The Doctor', perks: ['Overwhelming Presence', 'Monitor & Abuse', 'Overcharge']},
  { name: 'The Cannibal', perks: ['Franklin\'s Demise', 'Barbecue & Chili', 'Knockout']},
  { name: 'Huntress', perks: ['Beast of Prey', 'Territorial Imperative', 'Hex: Huntress Lullaby']},
  { name: 'The Nightmare', perks: ['Fire Up', 'Remember Me', 'Blood Warden']},
  { name: 'The Clown', perks: ['Pop', 'Bamboozle', 'Coulrophobia']},
  { name: 'Spirit', perks: ['Spirit Fury', 'Rancor', 'Hex: Haunted Grounds']},
  { name: 'The Legion', perks: ['Mad Grit', 'Iron Maiden', 'Discordance']},
  { name: 'The Plague', perks: ['Corrupt Intervention', 'Infectious Fright', 'Dark Devotion']},
  { name: 'Ghost Face', perks: ['Thrilling Tremors', 'Furtive Chase', 'I\'m All Ears']},
  { name: 'Demogorgon', perks: ['Surge', 'Mindbreaker', 'Cruel Limits']},
  { name: 'Oni', perks: ['Nemesis', 'Blood Echo', 'Zanshin Tactics']},
  { name: 'DeathSlinger', perks: ['Gearhead', 'Hex: Retribution', 'Dead Man\'s Switch']},
  { name: 'Executioner', perks: ['Forced Penance', 'Trail of Torment', 'Deathbound']},
  { name: 'Blight', perks: ['Dragon\'s Grip', 'Hex: Undying', 'Hex: Blood Favor']},
  { name: 'Twins', perks: ['Hoarder', 'Oppression', 'Coup de Grâce']},
  { name: 'Trickster', perks: ['Starstruck', 'No Way Out', 'Hex: Crowd Control']},
  { name: 'Nemesis', perks: ['Lethal Pursuer', 'Hysteria', 'Eruption']},
  { name: 'Cenobite', perks: ['No Holds Barred', 'Scourge Hook: Weeping Wounds', 'Hex: Fortune\'s Fool']},
  { name: 'Artist', perks: ['Grim Embrace', 'Scourge Hook: Pain Resonance', 'Hex: Pentimento']},
  { name: 'Onryo', perks: ['Call of Brine', 'Merciless Storm', 'Scourge Hook: Floods of Rage']},
  { name: 'Dredge', perks: ['Dissolution', 'Darkness Revealed', 'Septic Touch']},
  { name: 'The Knight', perks: ['Nowhere to Hide', 'Hubris', 'Hex: Face the Darkness']},
  { name: 'Mastermind', perks: ['Superior Anatomy', 'Awakened Awareness', 'Terminus']},
  { name: 'Xenomorph', perks: ['Alien Instinct', 'Ultimate Weapon', 'Rapid Brutality']},
  { name: 'The Good Guy', perks: ['Friends til the End', 'Hex: Two Can Play', 'Batteries Included']},
  { name: 'Dark Lord', perks: ['Dominance', 'Human Greed', 'Hex: Wretched Fate']},
  { name: 'Hound Master', perks: ['All-Shaking Thunder', 'No Quarter', 'Scourge Hook: Jagged Compass']},
  { name: 'The Ghoul', perks: ['Forever Entwined', 'Nothing But Misery', 'None are Free']},
  { name: 'Animatronic', perks: ['Haywire', 'Help Wanted', 'Phantom Fear']},
  { name: 'Krasue', perks: ['Ravenous', 'Wandering Eye', 'Hex: Overature of Doom']},
  { name: 'The Lich', perks: ['Languid Touch', 'Dark Arrogance', 'Weave Attunement']},
  { name: 'The Unknown', perks: ['Unbound', 'Undone', 'Unforeseen']},
  { name: 'The Singularity', perks: ['Forced Hesitation', 'Machine Learning', 'Genetic Limits']},
  { name: 'Skull Merchant', perks: ['Twack!', 'Leverage', 'Game Afoot']},
  { name: 'The Pig', perks: ['Surveillance', 'Scourge Hook: Hangman\'s Trick', 'Make Your Choice']},
  { name: 'Other', perks: ['Hex: No One Escapes Death', 'Bitter Murmur', 'Deerstalker', 'Distressing', 'Hex: Thrill of the Hunt',
    'Insidious', 'Iron Grasp', 'Scourge Hook: Monstrous Shrine', 'Shattered Hope', 'Sloppy Butcher', 'Spies from the Shadows', 'Unrelenting', 'Whispers']}

];

export const survivors = [
  { name: 'Kate Denson', perks: ['Dance With Me', 'Windows of Opportunity', 'Boil Over']},
  { name: 'Feng Min', perks: ['Technician', 'Lithe', 'Alert']},
  { name: 'Meg Thomas', perks: ['Quick & Quiet', 'Sprint Burst', 'Adrenaline']},
  { name: 'Dwight Fairfield', perks: ['Bond', 'Prove Thyself', 'Leader']},
  { name: 'Claudette Morel', perks: ['Empathy', 'Botany Knowledge', 'Self-Care']},
  { name: 'Nea Karlsson', perks: ['Balanced Landing', 'Urban Evasion', 'Streetwise']},
  { name: 'Laurie Strode', perks: ['Sole Survivor', 'Object of Obsession', 'Decisive Strike']},
  { name: 'Jeff Johansen', perks: ['Breakdown', 'Aftercare', "Distortion"]},
  { name: 'Nancy Wheeler', perks: ['Better Together', 'Fixated', 'Inner Strength']},
  { name: 'Sable Ward', perks: ['Invocation: Weaving Spiders', "Strength in Shadows", 'Wicked']},
  { name: 'Bill Overbeck', perks: ['Left Behind', 'Borrowed Time', 'Unbreakable']},
  { name: 'Jill Valentine', perks: ['Counterforce', 'Resurgence', 'Blast Mine']},
  { name: 'Vittorio Toscano', perks: ['Potential Energy', 'Fogwise', 'Quick Gambit']},
  { name: 'Adam Francis', perks: ['Diversion', 'Deliverance', 'Auto-Didact']},
  { name: 'Yui Kimura', perks: ['Any Means Necessary', 'Lucky Break', 'Breakout']},
  { name: 'Jonah Vasquez', perks: ['Overcome', 'Corrective Action', 'Boon: Exponential']},
  { name: 'Jane Romero', perks: ['Solidarity', 'Poised', 'Head On']},
  { name: 'Felix Richter', perks: ['Visionary', 'Desperate Measures', 'Built to Last']},
  { name: 'Ada Wong', perks: ['Wiretap', 'Reactive Healing', 'Low Profile']},
  { name: 'Jake Park', perks: ['Iron Will', 'Calm Spirit', 'Saboteur']},
  { name: 'Mikaela Reid', perks: ['Clairvoyance', 'Boon: Circle of Healing', 'Boon: Shadow Step']},
  { name: 'Gabriel Soma', perks: ['Troubleshooter', 'Made for This', 'Scavenger']},
  { name: 'Steve Harrington', perks: ['Babysitter', 'Camaraderie', 'Second Wind']},
  { name: 'Lara Croft', perks: ['Finesse', 'Hardened', 'Specialist']},
  { name: 'Trevor Belmont', perks: ['Eyes of Belmont', 'Exultation', 'Moment of Glory']},
  { name: 'David Tapp', perks: ['Tenacity', 'Detective\'s Hunch', 'Stake Out']},
  { name: 'David King', perks: ['We\'re Gonna Live Forever', 'Dead Hard', 'No Mither']},
  { name: 'Rebecca Chambers', perks: ['Better than New', 'Reassurance', 'Hyperfocus']},
  { name: 'Quentin Smith', perks: ['Wake Up!', 'Pharmacy', 'Vigil']},
  { name: 'Nicolas Cage', perks: ['Dramaturgy', 'Scene Partner', 'Plot Twist']},
  { name: 'Michonne Grimes', perks: ['Conviction', 'Last Stand', 'Teamwork: Throw Down']},
  { name: 'Taurie Cain', perks: ['Clean Break', 'Invocation: Treacherous Crows', 'Shoulder the Burden']},
  { name: 'Zarina Kassir', perks: ['Off the Record', 'Red Herring', 'For the People']},
  { name: 'Orela Rose', perks: ['Do No Harm', 'Duty of Care', 'Rapid Response']},
  { name: 'Ace Visconti', perks: ['Open-Handed', 'Up the Ante', 'Ace in the Hole']},
  { name: 'Yoichi Asakawa', perks: ['Parental Guidance', 'Empathic Connection', 'Boon: Dark Theory']},
  { name: 'The Troupe', perks: ['Bardic Inspiration', 'Mirrored Illusion', 'Still Sight']},
  { name: 'Ellen Ripley', perks: ['Chemical Trap', 'Light-Footed', 'Lucky Star']},
  { name: 'Leon Kennedy', perks: ['Bite the Bullet', 'Flashbang', 'Rookie Spirit']},
  { name: 'Alan Wake', perks: ['Champion of Light', 'Boon: Illumination', 'Deadline']},
  { name: 'Vee Boonyasak', perks: ['Ghost Notes', 'One-Two-Three-Four!', 'Road Life']},
  { name: 'Haddie Kaur', perks: ['Inner Focus', 'Residual Manifest', 'Overzealous']},
  { name: 'Yun-Jin Lee', perks: ['Fast Track', 'Smash Hit', 'Self-Preservation']},
  { name: 'Cheryl Mason', perks: ['Soul Guard', 'Blood Pact', 'Repressed Alliance']},
  { name: 'Ash Williams', perks: ['Flip-Flop', 'Buckle Up', 'Mettle of Man']},
  { name: 'Renato Lyra', perks: ['Blood Rush', 'Teamwork: Collective Stealth', 'Background Player']},
  { name: 'Élodie Rakoto', perks: ['Appraisal', 'Deception', 'Power Struggle']},
  { name: 'Rick Grimes', perks: ['Apocalyptic Ingenuinity', 'Come and Get Me!', 'Teamwork: Toughen Up']},
  { name: 'Thalita Lyra', perks: ['Friendly Competition', 'Teamwork: Power of Two', 'Cut Loose']},
  { name: 'Other', perks: ['Dark Sense', 'Déjà Vu', 'Hope', 'Kindred', 'Lightweight', 'No One Left Behind', 
    'Plunderer\'s Instinct', 'Premonition', 'Resilience', 'Slippery Meat', 'Small Game', 'Spine Chill', 'This is Not Happening', 'We\'ll Make It']} 

];
  
export const killerBuildThemes = {
      'Speed': ['Batteries Included', 'Furtive Chase', 'Machine Learning', 'Rapid Brutality', 'Unbound', 'Game Afoot', 'Devour Hope', 'Shadowborn', 'Hex: No One Escapes Death', 'Play with Your Food'],
      'Scourge': ['Scourge Hook: Floods of Rage', 'Scourge Hook: Gift of Pain', 'Scourge Hook: Hangman\'s Trick', 'Scourge Hook: Jagged Compass', 'Scourge Hook: Monstrous Shrine', 'Scourge Hook: Pain Resonance'],
      'Vaulting': ['Bamboozle', 'Dark Arrogance', 'Super Anatomy', 'Fire Up', 'Unbound', 'Dissolution', 'Cruel Limits', 'Hex: Crowd Control', 'I\'m All Ears', 'Zanshin Tactics'],
      'Stealth': ['Hex: Plaything', 'Unforeseen', 'Furtive Chase', 'Trail of Torment', 'Dark Devotion', 'Insidious', 'Beast of Prey', 'Hex: Overature of Doom', 'Tinkerer', 'Machine Learning', 'Deathbound', 'Hysteria'],
      'Gens-Slowing': ['Dying Light', 'Thanatophobia', 'Ruin', 'Hex: Pentimento', 'Dead Man\'s Switch', 'Corrupt Intervention', 'Scourge Hook: Gift of Pain', 'Hex: Wretched Fate', 'Deadlock', 'Grim Embrace', 'Merciless Storm', 'Thrilling Tremors', 'Hex: Huntress Lullaby'],
      'Gen-Damage': ['Pop', 'Surge', 'Eruption', 'Scourge Hook: Pain Resonance', 'Call of Brine', 'Oppression', 'Overcharge', 'Undone'],
      "End-Game": ['Remember Me', 'Blood Warden', 'Hex: No One Escapes Death', 'Haywire', 'No Way Out', 'Terminus', 'Ranchor','None Are Free'],
      'Basement': ['Insidious', 'Mad Grit', 'Agitation', 'Brutal Strength', 'Enduring', 'Iron Grasp', 'Monstrous Shrine', 'Territorial Imperative'],
      'Hex': ['Devour Hope', 'Face the Darkness', 'Thrill of the Hunt', 'Haunted Grounds', 'Pentimento', 'Blood Favor', 'Retribution','Crowd Control', 'Third Seal', 'Huntress Lullaby', 'Nothing But Misery', 'Overature of Doom', 'Ruin', 'Two Can Play', 'Undying', 'Wretched Fate', 'Hex: No One Escapes Death', 'Plaything'],
      'Info': ['Reveal the Darkness', 'Discordance', 'Barbecue', 'Nurse\'s Calling', 'Nowhere to Hide', 'Bitter Murmur', 'Infectious Fright', 'Lethal Pursuer', 'Floods of Rage', 'Iron Maiden', 'Predator', 'I\'m All Ears', 'Retribution', 'Nemesis', 'Deer Stalker', 'Lightborn', 'Weave Attunement', 'Wandering Eye', 'Zanshin Tactics', 'Twack!', 'Jagged Compass', 'Alien Instinct', 'Dragon\'s Grip', 'Gearhead', 'Friends til the End', 'Grim Embrace', 'Ranchor'],
      'Meme': ['Spirit Fury', 'Lightborn', 'Franklin\'s Demise', 'Phantom Fear', 'Distressing', 'Coup de Grace', 'Merciless Storm', 'No Quarter', 'Coulrophobia', 'Dragon\'s Grip', 'Hex: Haunted Grounds', 'Hex: Face the Darkness', 'Hoarder', 'Human Greed', 'Mad Grit', 'Whispers', 'Spies from the Shadows', 'Unnerving Presence', 'Unrelenting']
    };  

export  const survivorBuildThemes = {
      'Tunneling': ['Decisive Strike', 'Dramaturgy', 'Off The Record', 'Unbreakable', 'Overcome', 'Wicked', 'Deliverance', 'Shoulder the Burden', 'Borrowed Time', 'Head On', 'Moment of Glory', 'Second Wind', 'Pick your own Exhaust', 'Resurgence', 'Slippery Meat', 'Power Struggle', 'Flip Flop', 'Unbreakable', 'Buckle Up'],
      'Stealth': ['Distortion', 'Parental Guidance', 'Off the Record', 'Dance With Me', 'Ghost Notes', 'Iron Will', 'Cut Loose', 'Quick & Quiet', 'Urban Evasion', 'Fixated', 'Light-footed', 'Lucky Star', 'Low Profile', 'Lucky Break', 'Lightweight', 'Plot Twist', 'Calm Spirit', 'Diversion', 'Deception'],
      'Gens-Rushing': ['Stakeout', 'Weaving Spiders', 'Built To Last', 'HyperFocus', 'Bardic Inspiration', 'Prove Thyself', 'Leader', 'One, Two, Three', 'Resilience', 'Potential Energy', 'Technician', 'Fast Track', 'Friendly Competition', 'Overzealous', 'Deadline', 'Repressed Alliance'],
      'Chase': ['Finesse', 'Resilience', 'Windows of Opportunity', 'Lithe','Adrenaline','Balanced Landing', 'Sprint Burst', 'Dead Hard', 'Chemical Trap', 'Hope', 'Vigil', 'Fixated', 'Last Stand', 'Made for This', 'Overcome', 'Quick Gambit', 'Exulation', 'Champion of Light', 'Smash Hit'],
      'Boon': ['Boon: Circle Of Healing', 'Boon: Exponential', 'Boon: Dark Theory', 'Boon: Shadow Step', 'Boon: Illumination'],
      'Info': ['Deja Vu', 'Detective\'s Hunch', 'Wiretap', 'Object of Obsession', 'Alert', 'Kindred', 'Empathy', 'Bond', 'Clairvoyance', 'Dark Sense', 'Fogwise', 'Inner Focus', 'Tracherous Crows', 'Left Behind', 'Lucky Star', 'Premonition', 'Visionary', 'Wake Up!', 'Rookie Spirit', 'Plunderer\'s Instinct', 'Small Game', 'Still Light', 'Trouble Shooter', 'Better Together'],
      'Conviction': ['Conviction', 'Soul Guard', 'Plot twist', 'Unbreakable', 'Boon: Exponential', 'Tenacity', 'Flip-Flop', 'Power Struggle', 'No Mither'],
      'Healing': ['Auto-Didact', 'One, Two, Three', 'We\'ll Make it', 'Pharmacy', 'Self-Care', 'Empathy', 'Botany Knowledge', 'Clean Break', 'Inner Healing', 'Do No Harm', 'Empathic Connection', 'Blood Pact', 'Reactive Healing', 'Resilience', 'Resurgence', 'Solidarity', 'Strength in Shadows','We\'re Gonna Live Forever'],
      'Breakout': ['Breakout', 'Mettle Of Man', 'Self-Care', 'Background Player', 'For the People', 'Sabatuer', 'Champion of Light', 'Any Means Necessary', 'Flashbang'],
      'Meme': ['FlashBang', 'Mirrored Illusion', 'Scene Partner', 'Head On', 'Boiled Over', 'No Mither', 'Any Means Necessary', 'Bardic Inspiration', 'One, Two, Three', 'Object of Obsession', 'Diversion', 'For the People', 'Blast Mine', 'Dramaturgy', 'Plot Twist', 'Up the Ante', 'Ace in the Hole', 'Open-Handed']
    };